---@type LazySpec
return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "bash",
            "c",
            "cmake",
            "cpp",
            "css",
            "csv",
            "dockerfile",
            "git_config",
            "gitcommit",
            "gitignore",
            "go",
            "gomod",
            "gosum",
            "graphql",
            "helm",
            "html",
            "javascript",
            "json",
            "lua",
            "make",
            "markdown",
            "nginx",
            "python",
            "regex",
            "rust",
            "sql",
            "ssh_config",
            "tmux",
            "toml",
            "tsv",
            "tsx",
            "typescript",
            "vim",
            "xml",
            "yaml"
        },
    },
}
